### ISSUE TITLE
DBHandler createUniqueFullOMTUser is missing permissions for return requests

### ISSUE THREAD

**Issue by GTaenzer** [intershop/iom-test-framework#16]
**Affected version**
4.0.0

**Actual behavior**
the prefilled list of permissions tcr_fullomtclient is not up to date

**Expected behavior**
a full OMT client should bring all permissions required for the OMT

**To Reproduce**
1. create a user createUniqueFullOMTUser
2. try to view/manage return request within the OMT

AB#76836

**Comment by Philipp-Borchert-ISH** [comment]
(testcomment)
